default:
  image: node:20.11.0

before_script:
  - yarn install --frozen-lockfile

Build:
  stage: build
  script:
    - yarn lint
    - yarn build

Test:
  stage: test
  script:
    - yarn test
    - yarn test:coverage

Deploy-Staging:
  stage: deploy
  only:
    - staging
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=staging --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

Deploy-Production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
