default:
  image: node:20.11.0

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
  - npm install

Build:
  stage: build
  script:
    - npm run lint
    - npm run build

Test:
  stage: test
  script:
    - npm run test
    - npm run test:coverage

Deploy-Staging:
  stage: deploy
  only:
    - staging
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=staging --token=$VERCEL_TOKEN
    - vercel build --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --token=$VERCEL_TOKEN

Deploy-Production:
  stage: deploy
  only:
    - main
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - vercel build --prod --token=$VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token=$VERCEL_TOKEN
